name = "spinogambino-casinogame-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-casinogame.com"
HMAC_KEY = "6bb7331465160b99b909ef70c0c4a61f104112ce4661238ffacb21ede0ab4e15"
COOKIE_NAME = "50s"
PLAY_PATH = "go"
BUTTON_ID = "p89ea60b3c0b74d434107fb252f00dbd8"
GATE_SALT = "a675de7110201bed"
