name = "spinogambino-casinogame-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-casinogame.com"
HMAC_KEY = "6bb7331465160b99b909ef70c0c4a61f104112ce4661238ffacb21ede0ab4e15"
COOKIE_NAME = "qyn"
PLAY_PATH = "explore"
BUTTON_ID = "p89ea60b3c0b74d434107fb252f00dbd8"
GATE_SALT = "f291337f5cc6e06b"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "7i39"
CTA_SELECTOR = ".play-button"
